#application URl
url=http://opensource-demo.orangehrmlive.com/

#Browser Configuration
browser=chrome

#Credentials
username=Admin
password=admin123

#Timeouts(in seconds)
implicitWait=10
explicitWait=20